### PR TITLE
remove uses of predict(reshape = TRUE) for lightgbm models (fixes #40)

### LINKED ISSUE #40: 'reshape' argument to predict() will be removed in LightGBM v4.0.0
As of https://github.com/microsoft/LightGBM/pull/4971, `lightgbm:::predict.lgb.Booster()` no longer accepts the argument `reshape`. That pull request will be a part of LightGBM v4.0.0 (#34, https://github.com/microsoft/LightGBM/issues/5153).

`{bonsai}` passes `reshape = TRUE`  to `predict.lgb.Booster()` in several places.

https://github.com/tidymodels/bonsai/blob/ad9bb3955d12c4e3bc75b6ef90f8b13ea0d061a7/R/lightgbm.R#L271

https://github.com/tidymodels/bonsai/blob/ad9bb3955d12c4e3bc75b6ef90f8b13ea0d061a7/R/lightgbm.R#L297

https://github.com/tidymodels/bonsai/blob/ad9bb3955d12c4e3bc75b6ef90f8b13ea0d061a7/R/lightgbm.R#L304-L311

As a result, `{bonsai}`'s unit tests fail against `{lightgbm}`'s development version (confirmed with the approach mentioned in https://github.com/tidymodels/bonsai/issues/34#issuecomment-1186578635).

`{bonsai}`'s uses of `predict.lgb.Booster(..., reshape = TRUE ...)` should be removed.

### PR DESCRIPTION
**Pull request by jameslamb**
Fixes #40.

As described in that issue, the `reshape` argument to `predict.lgb.Booster()` has been removed in the development version of `{lightgbm}`. This PR proposes changes to make `{bonsai}` compatible with old and new versions of `{lightgbm}` by removing the use of that argument.

### Question for Reviewers

Is the following statement true?

> generating leaf-index or SHAP feature contributions directly using `{bonsai}` is not supported

If not, then this PR might need some changes. See https://github.com/microsoft/LightGBM/blob/44fe591a60d7427d64997c37b22768a92c97c47b/R-package/R/lgb.Predictor.R#L323-L326 for reference on why I'm asking.

Thanks for your time and consideration.

### CODE REVIEW

File: R/lightgbm.R [hunk 1]
```diff
@@ -260,6 +260,22 @@ sort_args <- function(args) {
...
+#
+# in versions after that release, lightgbm produces a numeric matrix with shape
+# [num_observations, num_classes]
+#
+# this function ensures that multiclass classification predictions are always
+# returned as a [num_observations, num_classes] matrix, regardless of lightgbm version
+reshape_lightgbm_multiclass_preds <- function(preds, num_rows) {
+    n_preds_per_case <- length(preds) / num_rows
+    if (is.vector(preds) && n_preds_per_case > 1) {
+        preds <- matrix(preds, ncol = npred_per_case, byrow = TRUE)
```
Comment (simonpcouch) [inline R/lightgbm.R:274]: I'm seeing:

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure (test-lightgbm.R:141:3): boost_tree with lightgbm ───────────────────
`{ ... }` threw an unexpected error.
Message: object 'npred_per_case' not found
```

Could you change this line to: 
```suggestion
        preds <- matrix(preds, ncol = npreds_per_case, byrow = TRUE)
```

**Review by simonpcouch — CHANGES_REQUESTED** [review]
Thanks for the PR! Implementation looks good, besides that one comment.

Confirming that

> generating leaf-index or SHAP feature contributions directly using {bonsai} is not supported

isn't from our documentation? Could you supply a reprex with lightgbm only showing the kind of output you're looking for?

**Comment by jameslamb** [comment]
Ok I think I've resolved the issues, sorry about that!
